# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newsletterrecipients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Editor',
            new_name='User',
        ),
    ]
