# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 13:54
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20190320_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='editor',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='article',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
